// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0DMrvFgmOzHDzEHAfySFgMd5-cAn0Ccw',
    appId: '1:777212624183:web:569448a4726eca8f1c6eb2',
    messagingSenderId: '777212624183',
    projectId: 'todo-e5465',
    authDomain: 'todo-e5465.firebaseapp.com',
    storageBucket: 'todo-e5465.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_I0L5-55cdh7KSH2UKwQp2HNdXSIqWc',
    appId: '1:777212624183:android:1c75c436b4e5702a1c6eb2',
    messagingSenderId: '777212624183',
    projectId: 'todo-e5465',
    storageBucket: 'todo-e5465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVsSCcsTPybj9eGYiVwm-5CWt0KLFCC8c',
    appId: '1:777212624183:ios:6f2377418106d0bd1c6eb2',
    messagingSenderId: '777212624183',
    projectId: 'todo-e5465',
    storageBucket: 'todo-e5465.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVsSCcsTPybj9eGYiVwm-5CWt0KLFCC8c',
    appId: '1:777212624183:ios:6f2377418106d0bd1c6eb2',
    messagingSenderId: '777212624183',
    projectId: 'todo-e5465',
    storageBucket: 'todo-e5465.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0DMrvFgmOzHDzEHAfySFgMd5-cAn0Ccw',
    appId: '1:777212624183:web:d1bbce14f4c158621c6eb2',
    messagingSenderId: '777212624183',
    projectId: 'todo-e5465',
    authDomain: 'todo-e5465.firebaseapp.com',
    storageBucket: 'todo-e5465.appspot.com',
  );
}
